### PR TITLE
Update Android (template) to Android 9.0

### PR DESCRIPTION
**Pull request by mallibone**
Updates the template for Android to target Android 9.0.

Uses the Support libraries v28 as described in this discussion #442.

### CODE REVIEW

**Comment by mallibone** [comment]
There seems to be an issue with the latest WPF XF platform project. I will check if it is reproducible with a C# XF app.

**Comment by SergejDK** [comment]
@mallibone 
aren't there changes between XF `4.0.0.425677` and `4.0.0.482894` or are they only internal of XF?

**Comment by mallibone** [comment]
> aren't there changes between XF `4.0.0.425677` and `4.0.0.482894` or are they only internal of XF?

As far as the [release notes](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.0/4.0.0-sr2#monday-june-3-2019---xamarinforms-400482894-400-service-release-2) go it includes only bugfixes and under the hood improvements.

**Comment by mallibone** [comment]
So seems like there was a bug in the previous service release of Xamarin.Forms. Should be good for a final look and test run.

**Comment by mallibone** [comment]
@SergejDK, I did not touch them intentionally and was not aware that they reference the NuGet packages locally. I'll have a look at them as soon as I get some time - having a bit of a busy week.

**Comment by mallibone** [comment]
@SergejDK after a quick peek into the solution. Am I right under the impression that paket is used to allocate the NuGet packages for the samples? It seems that this [file](https://github.com/fsprojects/Fabulous/blob/master/paket.dependencies) defines the NuGet versions for the samples.

**Comment by SergejDK** [comment]
@mallibone 
yes, I forgot about it. 
Surely the paket files should be checked and updated, too.

**Comment by mallibone** [comment]
@SergejDK surely it is then... I am not yet that familiar with paket but I will give my best to update the packages for the samples.

**Comment by TimLariviere** [comment]
@SergejDK @mallibone The samples crashing is unrelated to this PR.
I updated them in #446 
Will take a look at why they're crashing now.

**Comment by TimLariviere** [comment]
>Android Java.Interop Assembly not found.

@SergejDK Where did you have this error? In the templates or the samples?
Just tried to create a new projet with the updated template and everything is good

**Comment by SergejDK** [comment]
@TimLariviere 
was a failure on my side... 
needed to delete bin/obj, close and open again, rebuild - everything great. (just times where this has to be done....)

**Comment by TimLariviere** [comment]
Ok. I'm merging this then. :)
Thanks @mallibone!

**Pull request merged**
