### PR TITLE
3rd party binding generator

### LINKED ISSUE #441: Allow CodeGen to generate bindings for external libraries
Today, CodeGen scans existing dlls to automatically extract controls and properties, generating Fabulous-compatible wrappers for them.
The inheritance tree is used to propagate properties across controls (e.g. all controls inheriting from `Element` will have an `AutomationId` field such as `View.Button(automationId=XXX)` is possible).
CodeGen currently assumes the complete hierarchy will be found in the provided dlls.

It would be great to let people use CodeGen to generate wrappers for third party libraries (e.g. Maps, Telerik, etc.).
But for that, CodeGen need to be adapted to support additional inputs, under the form of already written bindings files, to let it know there's already a supported hierarchy on which it can depend.

E.g.
Generating a bindings file for a given dll:
`dotnet run fabulous-xf-generator.dll generate-bindings -d Xamarin.Forms.Maps.dll`

Generating wrappers for a previously created bindings file, with references to other bindings file:
`dotnet run fabulous-xf-generator.dll generate-wrappers -m Xamarin.Forms.Maps.json -o Fabulous.XamarinForms.Maps.dll`

With `Xamarin.Forms.Maps.json` (follows the same structure than `Xamarin.Forms.Core.dll`)
```json
{
  "assemblies": [
    "packages/neutral/Xamarin.Forms.Maps/lib/netstandard2.0/Xamarin.Forms.Maps.dll"
  ],
  "bindings": [
    "Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/Xamarin.Forms.Core.json"
  ],
  "outputNamespace": "Fabulous.XamarinForms",
  "types": [
     {
         "type": "Xamarin.Forms.Maps.Map",
         (...)
      }
  ]
}
```

The new part is the `"bindings"` field.

This would let users write things like `View.Map(automationId=XXX)`.

Initial message:
>If we want to support a new extension e.g. [Avalonia UI](http://avaloniaui.net/) we have to write a lot of code which can be generated by the Generator.
>So maybe we could use a seperate json file as the `Xamarin.Forms.Core.json` for each extension and let it run through this everyone could make their needed extension work on fabulous. 
There are some changes to make on the Generator part, too but didn't identify them yet.
>Then with a command like `./build.sh RunGenerator {extensionpath}` it can be run and the extension will be created. 
>After all the work for a sample have to be done manually.

### PR DESCRIPTION
**Pull request by TimLariviere**
Closes #441, #659 and #664

Glossary:
- Assembly = Content of a dll file
- Mapping file = JSON representation of an assembly, feeded to CodeGen through a Generator (e.g. Fabulous.XamarinForms.Generator). Example file: https://github.com/fsprojects/Fabulous/blob/master/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json
- Bindings = The generated F# code allowing to use the 3rd party Xamarin.Forms controls with Fabulous (DynamicViews)

As explained by https://github.com/fsprojects/Fabulous/issues/441#issue-453887130, the idea is to write a mapping file with references to other mapping files.
This allows anyone to write their own mapping file to generate bindings for 3rd party libs (like SyncFusion) with the inherited properties/events from Xamarin.Forms.
It's this last part that isn't currently possible.

Writing the following mapping file
```json
{
  "assemblies": [
    "path/to/Xamarin.Forms.Core.dll",
    "path/to/SyncFusion.dll"
  ],

  // This is the new field. It is optional and can contain one or more mapping files
  "baseMappingFiles": [
    "path/to/Xamarin.Forms.Core.json" // Found in the Fabulous.XamarinForms repository
  ],

  "outputNamespace": "Fabulous.XamarinForms.SyncFusion",
  "types": [
    {
      "type": "Syncfusion.Buttons.XForms.SfButton",
      "properties": [
        {
          "source": "IsCheckable"
        },
        {
          "source": "ShowIcon"
        }
      ]
    },
    (...)
  ]
} 
```

And passing it to Fabulous.XamarinForms.Generator, will result in the matching F# binding code with all the same declared parameters of the inherited button control + the new declared parameters.

```fs
View.SfButton(
    text = "SyncFusion button", // Comes from Xamarin.Forms
    showIcon = true // Comes from SyncFusion
)
```

cc @xperiandri

### CODE REVIEW

**Comment by TimLariviere** [comment]
Currently, it's only a first draft.
I managed to generate [this F# binding code](https://github.com/fsprojects/Fabulous/blob/b4094329bd81d850d7f12e8bfee5fa9ba9d9d21e/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Fabulous.XamarinForms.fs) from [this mapping file](https://github.com/fsprojects/Fabulous/blob/b4094329bd81d850d7f12e8bfee5fa9ba9d9d21e/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Fabulous.XamarinForms.json).
The `TestButton` control is declared [here](https://github.com/fsprojects/Fabulous/blob/b4094329bd81d850d7f12e8bfee5fa9ba9d9d21e/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/CustomControls.fs#L11-L19)

It's only missing the correct `open` statements to be compilable. But should be working once added manually.

**Comment by TimLariviere** [comment]
Managed to successfully moved OxyPlot, SkiaSharp and VideoManager under automatically generated bindings

**Comment by TimLariviere** [comment]
Implemented #659 and #664 for FFImageLoading

**Comment by TimLariviere** [comment]
This PR should be ok now.

@SergejDK Could you please review it and let me know what you think?
Thanks.

**Comment by SergejDK** [comment]
@TimLariviere 
About #664 should we check the `ViewUpdaters.fs`, too? I mean we use the defaultValue there and maybe we should use `ClearProperty` in this file. What dou you think?

**Comment by TimLariviere** [comment]
>About #664 should we check the ViewUpdaters.fs, too? I mean we use the defaultValue there and maybe we should use ClearProperty in this file. What dou you think?

Yes! You're completely right. Forgot to check this file.
Will do.

**Pull request merged**
