### PR TITLE
Upgrade samples to Android Pie (9.0)

### PR DESCRIPTION
**Pull request by TimLariviere**
Partial cover of #442

Update the samples to compile for Android Pie (9.0) instead of Oreo (8.1).
Also samples now start support at Android Lollipop 5.0 (API Level 21) instead of Android KitKat 4.4

This is required to be able to use Shell and Visual.

### CODE REVIEW

**Comment by SergejDK** [comment]
2 things: 

1. Maybe we should write sth. in the docs that the `.fake` directory should be deleted else it won't work when running `./build.sh` - it will fail at `BuildFabulous`.

2. The Calculator App does not work anymore. Can't make it work on my device (Motorola G6 Plus).

**Comment by TimLariviere** [comment]
>Works now. Configurationmanager needed to provide Calculator.Droid (wasn't set as porvided like the other projects); rebuild and restart after this worked.

@SergejDK I'm not sure to understand.
What do you mean by "ConfigurationManager needed to provide Calculator.Droid"?

**Comment by SergejDK** [comment]
@TimLariviere have it on german so i hope the follwoing screenshot shows what i mean:
grafik
grafik

**Comment by SergejDK** [comment]
the right column i think translated should be "provided" or "supplied"...
If you check this it works.

**Comment by TimLariviere** [comment]
Ah ok. In English, the columns are "Build" and "Deploy".
So makes sense, it weren't working.

Visual Studio prevented the sample to be deployed on your device.

**Pull request merged**
