### PR TITLE
Xamarin Forms Upgrade 4.4 -> 4.5

### PR DESCRIPTION
**Pull request by SergejDK**
This List is just for me to check if I go the most ...
List of Changes: 
- [x] Xamarin.Forms.Animation 
- [x] BindableObject
- [x] CarouselView
- [x] FontImageSource
- [x] IndicatorView
- [x] ItemsView
- [x] Page
- [x] SelectableItemsView
- [x] Setter
- [x] Shell
- [x] ShellContent
- [x] Stepper
- [x] SwipeItems
- [x] VisualElement
- [x] VisualState
- [x] ExportFontAttribute
- [x] FileMediaSource
- [x] EmbeddedFont
- [x] MediaElement
- [x] UriMediaSource

### CODE REVIEW

**Comment by Happypig375** [comment]
Fixes #682

**Comment by SergejDK** [comment]
@Happypig375 
thanks forgot this ...

**Comment by TimLariviere** [comment]
@SergejDK Seems like we had the same idea 😅 
I did a branch yesterday we some of XF 4.5, though I'm currently more focused on Android 10 (I have a few problems between Paket and Fake about that...)

**Comment by TimLariviere** [comment]
See #700 
Not finished but there's my views on what should be in the JSON file. Maybe interesting on comparing our 2 files.

I'll continue on Android 10 for my part.
You can use your PR for XF 4.5 support.

**Comment by SergejDK** [comment]
I see you were ahead of me :D 

Some bigger changes on where to set the versions :) 
Was just starting with adding support for 4.5 ... I'll take your PR and check where I can take your work :)

**Pull request closed without merging**
