### PR TITLE
Added testing for macOS & GTK templates

### PR DESCRIPTION
**Pull request by TimLariviere**
As discussed in #287, we were not testing the macOS and GTK templates in the build process.

### CODE REVIEW

**Comment by TimLariviere** [comment]
Travis CI seems happy with this.

Oddly enough, on my machine (macOS), when building the GTK project it deletes the dll of the shared project.
Thus the macOS project fails due to not being able to find the dll.

Do someone has a similar problem? @mallibone

**Comment by dsyme** [comment]
This is fantastic.  I checked the travis log and it is indeed building macOS
```
[39;49m[39;49m[37m  /Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/fsharp/fsc.exe -o:obj/Debug/testapp269.macOS.exe
```

**Comment by mallibone** [comment]
@TimLariviere interesting I will give it a spin later today, I did not have any issues back before we were "fighting" with Travis 🙃

I am looking forward to running this PR on the Azure DevOps PR.

**Comment by mallibone** [comment]
@TimLariviere I pulled this branch and ran `./build.sh Test` without any issues locally on my Mac running Mojave 10.14.2, latest XCode and Visual Studio (stable). But it does seem odd that it fails on your end.

**Comment by TimLariviere** [comment]
Well I'm glad it's only on my end.
Maybe VS2019 is doing something funny.

**Pull request merged**
