### PR TITLE
Fix Android samples not deploying in some configurations

### PR DESCRIPTION
**Pull request by TimLariviere**
Some samples were not able to deploy on specific configurations (Debug/Release, AnyCPU/iPhone/etc.)

This is now fixed. All samples build and deploy the same.

@SergejDK This should fix the issue you had

### CODE REVIEW

**Comment by SergejDK** [comment]
Looks good! 
Works! - Thanks!

Both Columns for UWP are empty - is this right?

**Comment by TimLariviere** [comment]
UWP can only be built and deployed for x86 and x64
It does not support AnyCPU (and derived ARM/iPhone configurations)

**Comment by SergejDK** [comment]
Okay, great. Didn't know exactly about it.
Thanks :)

**Comment by SergejDK** [comment]
Thanks, again!

**Pull request merged**
