### PR TITLE
Add a TextChanged Event to the EntryCell

### PR DESCRIPTION
**Pull request by garethhubball**
Started work on the `TextChanged` event to start fixing #225 - it seems to work in WPF but not in iOS/Android. The `Text` property seems to be ignored in iOS/Android and needs looking into.

Please don't merge this yet as it does not work!

### CODE REVIEW

**Comment by TimLariviere** [comment]
PR #226 needs to be merge before this one.
Also a rebase will be needed once done.

**Comment by TimLariviere** [comment]
One last thing :)
You need to add a reference to `Fabulous.CustomControls.dll` in the template projects and samples projects as well, like you did for `AllControls`

**Comment by TimLariviere** [comment]
I think I know why this doesn't work on Android and iOS.
You're hiding the base property `Text` of EntryCell with the one you declared in CustomEntryCell.
Android and iOS still refer to `EntryCell.Text`, and without override they won't call your code.

For some reason, WPF is OK with that though.

**Comment by garethhubball** [comment]
Thank you - I'll have a look at this tonight as well as cleaning up the PR.

**Comment by garethhubball** [comment]
> I think I know why this doesn't work on Android and iOS.
> You're hiding the base property `Text` of EntryCell with the one you declared in CustomEntryCell.
> Android and iOS still refer to `EntryCell.Text`, and without override they won't call your code.
> 
> For some reason, WPF is OK with that though.

Ahhh, Jsut had a look at Xamarin.Forms and the base `Text` property isn't virtual, so while we can hide it, we can't simply override it. I wonder if I need to have a closer look at trying to do this in Xamarin.Forms directly and just bubble up the change once it's in there.

**Comment by TimLariviere** [comment]
Another way you could do it is by subscribing to the PropertyChanged event of EntryCell yourself.
And if the property changed is `Text`, then you can trigger your TextChanged event.

**Comment by garethhubball** [comment]
Why did I not think of that? Thank you!!!

**Comment by garethhubball** [comment]
This now works across all three platforms. If there's anything I can do to make any merge easier please let me know - I still haven't really got the hang of PRs, Git nor working in open source yet so apologies if and when I go wrong.

**Comment by TimLariviere** [comment]
Build is failing.
Could you add a reference to Fabulous.CustomControls in the fsproj of the templates?
https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.Android/NewApp.Android.fsproj
https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.WPF/NewApp.WPF.fsproj
https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.iOS/NewApp.iOS.fsproj
https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.macOS/NewApp.macOS.fsproj

If you want to validate these changes without waiting for Travis CI, you can run `.\build.cmd Test` on your machine

**Comment by TimLariviere** [comment]
And finally, it would be great if you could move Fabulous.CustomControls into the `src` folder.

No need to exclude `Fabulous.CustomControls` from the `Build` step. This step will run `dotnet pack` on all src/**/*.fsproj, which we'll need to push the new project in NuGet.
You can just change your `BuildCustomControls` to do a `MSBuild Release` instead (only generate the dll for the Generator). Make sure you have the correct path to the dll in the bindings json afterwards.

**Comment by TimLariviere** [comment]
This looks good. Well done!
I'll do a little preparation work and then will be able to release this in the next version :)

**Pull request merged**
