### PR TITLE
XF Update 3.6

### LINKED ISSUE #357: Upgrade to Xamarin.Forms 3.6
Xamarin.Forms 3.6 has been released. Fuget API changes since 3.5 [here](https://www.fuget.org/packages/Xamarin.Forms/3.6.0.220655/lib/netstandard2.0/diff/3.5.0.169047/).

### PR DESCRIPTION
**Pull request by SergejDK**
fix #357 

2 Functions are open right now the rest is in it. 
On the Slider class: `DragStarted` and `DragCompleted`

### CODE REVIEW

**Comment by aspnetde** [comment]
One question: Did all the visual elements already get the `visual="..."` attribute with the 3.5 update? I can't tell from the changeset. This would be necessary to apply the [Material Visual](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual).

**Comment by SergejDK** [comment]
I don't think that in 3.5 there was the attribute. 
This should be in 3.6 - will test it in the `AllControls.fs`.

I don't know if we need an Flag here as for Shell etc.

**Comment by SergejDK** [comment]
@aspnetde 
Normally this was included in 3.5 but I didn't see that. I will include it with this update.

**Comment by aspnetde** [comment]
Thanks a lot. Just in time for me (really).

**Comment by SergejDK** [comment]
@TimLariviere I think I got it all.

**Comment by TimLariviere** [comment]
@SergejDK Well, that was quick. 😄
I checked and everything is covered. Great job!

I will integrate it to v0.34 then :)

**Comment by SergejDK** [comment]
@TimLariviere 
sure the guys are waiting so we need to be quick :D

**Pull request merged**
