### PR TITLE
Tell users to add the Oxyplot MyGet feed as a NuGet restore feed

### PR DESCRIPTION
**Pull request by Happypig375**
The Xamarin Oxyplot packages are not likely to be further updated given https://github.com/oxyplot/oxyplot/issues/1274, so why not give clearer instructions based on the current situation?

### CODE REVIEW

**Comment by TimLariviere** [comment]
@Happypig375 Would it make sense to downgrade the package we use, and only target nuget.org?

**Comment by Happypig375** [comment]
[Diff of oxyplot/oxyplot from 1.1.0-unstable0011 to 1.1.0-unstable0013](https://github.com/oxyplot/oxyplot/compare/5bbea0be62d2cc1ca40dd06212400af25b177c3a..ddd083897dc124be17d120a3db63ae565c68aaa7)
[Diff of oxyplot/oxyplot-xamarin from 1.1.0-unstable0011 to 1.1.0-unstable0013](https://github.com/oxyplot/oxyplot-xamarin/compare/e0ca6f98442074fdeb0b5240f7209cbb05ea26a7..b4cfbdefd43e3d53ddbe14a7d231e0c2ded03e6c)

I don't think there's much of a difference in Oxyplot.Xamarin.Forms 1.1.0-unstable0013 apart from requiring an unstable version of Oxyplot.

**Comment by Happypig375** [comment]
There might be something overlooked by me though.

**Comment by TimLariviere** [comment]
@Happypig375 Ok, great. Will try to see if the samples run with `1.1.0-unstable0011`.
If there's no issue, I suggest we downgrade.
It will be easier for everyone.

What do you think?

**Comment by Happypig375** [comment]
We might be able to downgrade even further to `1.0.0`, the only stable version on NuGet. That way, we will be able to potentially remove undiscovered bugs due to an "unstable" version.

**Comment by TimLariviere** [comment]
Created PR #387 with the downgrade.
Building the source code is OK, though I haven't tested it in an app.

**Comment by Happypig375** [comment]
Superseded by #387

**Pull request closed without merging**
