### PR TITLE
Reference work on XF 4.5

### PR DESCRIPTION
**Pull request by TimLariviere**

### CODE REVIEW

**Comment by Happypig375** [comment]
Fixes #682

**Comment by TimLariviere** [comment]
IndicatorView will be a PITA.
They change it from having a CarouselView property to CarouselView having a IndicatorView property, though the value is still stored in the IndicatorView instance.

It means we won't be able to clear the value easily, or even at all...

**Comment by SergejDK** [comment]
@TimLariviere 
do you think we need to handle those methods `OnChildRemoved `

**Comment by TimLariviere** [comment]
@SergejDK No, I don't think we need to. It's not a user-triggered event so it's not really useful in Fabulous.

**Comment by TimLariviere** [comment]
Replaced by #709

**Pull request closed without merging**
