### PR TITLE
fix interpreter bugs and make it pass tests

### PR DESCRIPTION
**Pull request by dsyme**
Fix most bugs in #281 

@TimLariviere It seems like a few of the Cli.Tests weren't passing, and so I patched things up - odd how many were failing.  Are they under CI?  I checked `build.fsx` and it looks like they are

### CODE REVIEW

**Comment by TimLariviere** [comment]
Yes, they're under CI. But only Travis CI (macOS) actually runs them (FAKE target "Test").

Do you know which ones were failing?
Just tried to run them on my machine (macOS) and a VM (Windows), all are passing.

**Comment by dsyme** [comment]
> Do you know which ones were failing? Just tried to run them on my machine (macOS) and a VM (Windows), all are passing.

Ah ok, it might be that my first fix caused others to fail, and so on - I didn't test them clean.  Now all are passing and the new tests are well, so all are good

**Comment by TimLariviere** [comment]
@dsyme Is this PR ready to be merged?

**Comment by dsyme** [comment]
@TimLariviere Yes it is, thanks

**Pull request merged**
