### PR TITLE
Added type annotations on the mkProgram functions

### PR DESCRIPTION
**Pull request by pauldorehill**
When starting to using the `Program.mkProgram`, `Program.mkSimple` the intellisense/compiler currently show generic type names like `'a` which makes it hard to work out what your functions need to do:

image

So I've added the type annotations to make it a bit clearer:

image

### CODE REVIEW

**Comment by pauldorehill** [comment]
As a side note while doing this I was also curious on the `Program` type:
```
type Program<'model, 'msg, 'view> = 
    { init : unit -> 'model * Cmd<'msg>
      update : 'msg -> 'model -> 'model * Cmd<'msg>
      subscribe : 'model -> Cmd<'msg>
      view : 'view
      debug : bool
      onError : (string * exn) -> unit }
```
Does the `view` property need to be generic? I'm just getting started with Xamarin.Forms so there may well be an obvious reason I don't know... but I couldn't see a reason why it can't be defined as:
```
type Program<'model, 'msg> = 
    { init : unit -> 'model * Cmd<'msg>
      update : 'msg -> 'model -> 'model * Cmd<'msg>
      subscribe : 'model -> Cmd<'msg>
      view : 'model -> ('msg -> unit) -> ViewElement
      debug : bool
      onError : (string * exn) -> unit }
```
This would then make the required function signatures clearer still? If you agree I can update the commit?

**Comment by TimLariviere** [comment]
>Does the `view` property need to be generic?
Maybe it's related to the StaticView part, but this seems more like an early code that haven't needed updating since then.
Makes sense to enforce a specific type annotation, clearer that way.

**Comment by pauldorehill** [comment]
Ok, I'll update the pull request with the types updated.

**Comment by dsyme** [comment]
Yes the generic 'view  is related to the half-elmish support 

I wonder if we should duplicate out the half-elmish support into an entirely separate DLL.  Or deprecate/remove it - though there are still people who advocate it as a stepping stone.

**Comment by pauldorehill** [comment]
If you were to remove it I guess the question is `whats the target audience for Fabulous?`. Maybe initially move it to a separate project/dll?

**Comment by TimLariviere** [comment]
Today, most of the work goes to the full-elmish approach. We're not actively supporting half-elmish.
I think we still need to keep it around, but maybe we should go as far as putting it in a different Github project?

That way, we separate it from Fabulous and say we won't support it further.
But if people think it has its place, they will be able to maintain it.

>Maybe initially move it to a separate project/dll? If you want to move I can add as part of this pull request?

I would prefer to merge this PR as-is. It's useful enough.
And do another PR later to add type annotation to `'view`.

**Comment by TimLariviere** [comment]
Merging.
We will separate the half-elmish in a another PR later, before changing type annotation for `'view`

**Pull request merged**
