### PR TITLE
Adding StyleClass to VisualElement

### PR DESCRIPTION
**Pull request by davidglassborow**
see #205

### CODE REVIEW

**Comment by TimLariviere** [comment]
Well done!
Do you know if there's some limitation with changing/removing css?

I tried some cases with the AllControls app, but it doesn't seem to update correctly.
- "cssCallout" changed to "cssRed" (.cssRed { color: Red; })
- "cssCallout" changed to ""

They don't update visually, even though the control itself is properly updated

**Comment by davidglassborow** [comment]
Maybe an XF bug ?  Looking at https://github.com/xamarin/Xamarin.Forms/issues/3824, maybe related.  Same issue seems to exist with StyleId.

CSS is pretty new in XF, so maybe we can assume a XF limitation for the moment ?

Doesn't affect my use case for the moment so I'm keen to get this merged and nuget updated if your happy ?

**Comment by dsyme** [comment]
The `styleClass` parameter should be added for each of the three extensions, e.g. here https://github.com/fsprojects/Fabulous/blob/master/extensions/Maps/Xamarin.Forms.Maps.fs#L32

It's annoying to have to do this but not too hard.

**Comment by dsyme** [comment]
Looks like the Unix build is failing, I'm not totally sure why

**Comment by TimLariviere** [comment]
Yes, noticed it as well.
It fails for a different reason each time (aapt missing, missing NuGet package, etc.), but most of the times it works.

**Comment by davidglassborow** [comment]
CI / Paket failing for some reason.  That package is available on nuget so no idea why travis is failing.

```
Paket failed with
-> Could not download OpenTK.GLControl 3.0.1.
-> Couldn't get package details for package OpenTK.GLControl 3.0.1 on https://api.nuget.org/v3/index.json.
```

**Pull request merged**
