### PR TITLE
Made fscd a dotnet CLI tool "fabulous-cli" + Unit tests ran on FAKE build

### PR DESCRIPTION
**Pull request by TimLariviere**
Making this PR mostly to test CI.

Fixing `fscd.Tests` to run on all platforms and run it as part of the build process.
2 tests have been disabled because of a known limitation of FSharp.Compiler.Service.

Also had to make `fscd.Tests` a .NET Core library to run outside of Visual Studio (FAKE 5 can't run MSTest v2 on MacOS, even though VSfM can run it)
So I also made `fscd` a .NET Core app which change the way we run it
`mono fscd.exe --watch` => `dotnet fscd.dll --watch`

### CODE REVIEW

**Comment by TimLariviere** [comment]
Tests are running. Great.

I'll take a look at converting `fscd` as a dotnet global tool.
Didn't noticed the bug #119, FsPickler as been replaced by Newtonsoft.Json.

**Comment by TimLariviere** [comment]
@nosami @jimbobbennett @dsyme 
Could you give a try to the new dotnet cli tool, please?
The FileSystemWatcher seems to work every time now.

Steps to install your own fabulous-cli
```
cd src/Fabulous.Cli
dotnet pack
dotnet tool install -g --add-source bin/Debug/ fabulous-cli
cd /path/to/your/app
fabulous --watch --webhook:http://localhost:9867/update
```

Thanks

**Comment by nosami** [comment]
I just gave this a try.

Changes to any file in the source folder were detected immediately and it was very stable. 💯

**Comment by nosami** [comment]
[I tried to do this a few months ago](https://github.com/fsprojects/Fabulous/issues/119) but back then there were serialization differences between Mono running on the device and dotnet running in the watcher that meant this wasn't possible back then.

On dotnet core, the serialized types referred to System.Private.CoreLib which isn't available on Mono.

I'm not sure if this issue has been resolved - I need to check if there are issues in the emulator when refreshing.

**Comment by nosami** [comment]
I updated Elmish.Calculator to the latest Fabulous dependencies and it is working really well, so not sure what changed between July and Now :)

Live reload is now extremely quick too.

fscd

**Comment by TimLariviere** [comment]
That's really good to hear. :)

**Comment by dsyme** [comment]
@TimLariviere @nosami Sorry I've been a bit out of the loop due to a trip to Redmond.  Hoping to get back into Fabulous in the next few days before Xmas vacation

**Comment by dsyme** [comment]
I looked through.... this work is absolutely .... yes... you know what I'm about to say...

Absolutely Fabulous!

**Comment by jimbobbennett** [comment]
Just tried it on one of my projects and get errors, but also got errors with the old watcher. Seems it doesn’t like a timer subscription... will raise an issue for it.

**Comment by TimLariviere** [comment]
Ok, this sounds good. Did another successful set of manual tests with fabulous-cli. :)
I'm merging it and will release v0.29

There's a lot of limitations with LiveUpdate I think we should track as issues, to see if we can fix them.
E.g. multi-files projects, changes to fsproj, current model reloading and messages not dispatching after a reload, to name a few.

**Pull request merged**
