### PR TITLE
Add support for MAUI

### PR DESCRIPTION
**Pull request by TimLariviere**
Now that [MAUI Release Candidate 1 is released](https://devblogs.microsoft.com/dotnet/dotnet-maui-rc-1/), I'm taking a stab at supporting it.

IDE support on macOS is completely absent but running via command line works.
```
// iOS
dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=59F2133A-63ED-4791-A795-8F23C61E678B

// Android
dotnet build -t:Run -f net6.0-android

// Mac Catalyst
dotnet build -t:Run -f net6.0-maccatalyst
```

### CODE REVIEW

**Comment by edgarfgp** [comment]
Thanks so much  . I will play a long and see if we can make some progress . :)

**Comment by TimLariviere** [comment]
Managed to get the label displayed

**Comment by TimLariviere** [comment]
Trying to make some progress on the Maui support. Getting closer to get a running sample, but still quite far from having anything usable.

Current state:
I can display a Label and a Button inside a Window. The button sends the events correctly but Maui isn't updating the UI despite calling `handler.UpdateValue("Text")`.
Also, VStack/HStack are not displaying anything.

**Comment by TimLariviere** [comment]
... and the IDEs that crash in a way or another when I'm debugging aren't making anything simpler.

**Comment by TimLariviere** [comment]
Was missing the synchronization with the main thread. Now it's working 🎉 
https://user-images.githubusercontent.com/6429007/184471837-5f2af812-caa2-43a8-939c-fe8b3b40c3eb.mp4

**Comment by edgarfgp** [comment]
Nice . Let me know if there is any thing I can help ?

**Comment by edgarfgp** [comment]
While adding support for Maui . Could we review the Light and Dark support for text images , maybe also the styling ?

**Comment by TimLariviere** [comment]
>Nice . Let me know if there is any thing I can help ?

Thanks for asking :)
Right now, I'm still struggling to understand how controls work in Maui.
If you feel like it, you can use another brain to reverse-engineer Maui to get the Hello World sample running 😄 

>While adding support for Maui . Could we review the Light and Dark support for text images , maybe also the styling ?

Sure. Do you have an idea how you would do it differently?

**Comment by TimLariviere** [comment]
image

**Comment by TimLariviere** [comment]
https://github.com/dotnet/maui/issues/5835

**Comment by TimLariviere** [comment]
Still have some layout issues, but I made some progress

**Comment by TimLariviere** [comment]
I ported the TicTacToe sample. It's not exactly the same than the XF one because Maui.Core lacks some features: `OnSizeAllocated` and `RequestedThemeChanged`.

**Comment by TimLariviere** [comment]
The direct support for Maui (without Maui.Controls & XAML) has been moved to https://github.com/fsharp-mobile/Fabulous.Maui

**Pull request closed without merging**
